# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Felipe Espinoza
email: fespinozacast@gmail.com
description: ''
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fespinozacast.com" # the base hostname & protocol for your site
twitter_username: fespinozacast
github_username:  fespinoza

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Outputting
permalink: :title

